export const CRYPTO_LOGOS: Record<string, string> = {
  BTC:   'https://assets.coingecko.com/coins/images/1/large/bitcoin.png',
  ETH:   'https://assets.coingecko.com/coins/images/279/large/ethereum.png',
  SOL:   'https://assets.coingecko.com/coins/images/4128/large/solana.png',
  BNB:   'https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png',
  XRP:   'https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png',
  ADA:   'https://assets.coingecko.com/coins/images/975/large/cardano.png',
  DOGE:  'https://assets.coingecko.com/coins/images/5/large/dogecoin.png',
  AVAX:  'https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png',
  DOT:   'https://assets.coingecko.com/coins/images/12171/large/polkadot.png',
  MATIC: 'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png',
  SHIB:  'https://assets.coingecko.com/coins/images/11939/large/shiba.png',
  LTC:   'https://assets.coingecko.com/coins/images/2/large/litecoin.png',
  UNI:   'https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png',
  LINK:  'https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png',
  ATOM:  'https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png',
  XLM:   'https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png',
  ALGO:  'https://assets.coingecko.com/coins/images/4380/large/download.png',
  VET:   'https://assets.coingecko.com/coins/images/1167/large/VeChain-Logo-768x725.png',
  ICP:   'https://assets.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png',
  FIL:   'https://assets.coingecko.com/coins/images/12817/large/filecoin.png',
  APT:   'https://assets.coingecko.com/coins/images/26455/large/aptos_round.png',
  ARB:   'https://assets.coingecko.com/coins/images/16547/large/photo_2023-03-29_21.47.00.jpeg',
  OP:    'https://assets.coingecko.com/coins/images/25244/large/Optimism.png',
  SUI:   'https://assets.coingecko.com/coins/images/26375/large/sui_asset.jpeg',
  SEI:   'https://assets.coingecko.com/coins/images/28205/large/Sei_Logo_-_Transparent.png',
}
